### PR TITLE
Add support for ES2015 in server code

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @ndarilek 

I'm not sure that babel-core is the solution since it will only works for the server.js file and not the required files.

I think a solution like [backpack](https://github.com/palmerhq/backpack) might be a solution.

**Comment by ndarilek** [comment]
It isn't working in required files for you? Perhaps I also need 
babel-register installed, though I thought the use of babel-node would 
sort that out. Seems to work fine in my GraphQL schema files which a) 
are imported into the server and b) use `import` themselves.

**Comment by Atinux** [comment]
I will try manually and if it's working I'll merge it :)

Thank you for helping us to make the express starter better!

**Comment by Atinux** [comment]
Thank you @ndarilek

**Pull request merged**
